### ISSUE TITLE
Zscaler list false positives

### ISSUE THREAD

**Issue by notracking** [scafroglia93/blocklists#1]
Found another 2, see https://github.com/notracking/hosts-blocklists-scripts/blob/master/hostnames.whitelist.txt for more details.

vs.login.msa.akadns6.net
login.msa.akadns6.net

**Comment by scafroglia93** [comment]
1- Done
https://github.com/scafroglia93/hosts-blocklists/commit/7fb539c7d79ca820cecae6374c083b8cc5476c5f

2- It would be interesting to integrate these lists by excluding the IPs inside them.
https://github.com/stamparm/maltrail/tree/master/trails/static/malicious
https://github.com/stamparm/maltrail/tree/master/trails/static/malware
https://github.com/stamparm/maltrail/tree/master/trails/static/suspicious

The next thing I'm doing is sorting lists by topic
They are really well done with a lot of reference so it is possible to go back to the source if there were problems

Keep me update (scafroglia57@gmail.com)

**Comment by notracking** [comment]
I believe that most of those (active) hosts are already covered in: https://raw.githubusercontent.com/stamparm/blackbook/master/blackbook.txt

I took various samples from those sources and notice that only the un-registered domains where not present in the blackbook list.

**You have to be very carefull with these type of malware lists, as they tend to include a lot of legit services / websites.

**Comment by scafroglia93** [comment]
We can try inserting the lists progressively in order to do some tests.
They are all referenced for which the false positive is reduced to a minimum

I am available for a test

**Comment by scafroglia93** [comment]
Are you agree with me ?

**Comment by scafroglia93** [comment]
Disappear ;) LOL
