### ISSUE TITLE
You should unblock ieji.de and koyu.space

### ISSUE THREAD

**Issue by austinhuang0131** [scafroglia93/blocklists#15]
Commit https://github.com/scafroglia93/blocklists/commit/e327ff50286980a457a94231184785c5dfbf222d

Having one bad account on a public platform does not justify a block against the platform itself, especially when the admins were not notified of this at publishing, and when they do become aware, the accounts have been removed.

cc. @solsocog @koyuawsmbrtn

**Comment by koyuawsmbrtn** [comment]
Can confirm. Please contact me before putting my site on your blocklist or publishing news articles about it.

**Comment by SolSoCoG** [comment]
Deleted it as soon as I was notified of the abuse, I'd also welcome an attempt of contacting beforehand.

**Comment by scafroglia93** [comment]
I am just going back to the reports made by the zsscaler team

I find the report very rude and in any case no one forces you to follow my work.

The problem has been solved; I advise you not to use my blocklists for the future 

Thanks
