### ISSUE TITLE
blocklists-sentinelone.txt is problematic

### ISSUE THREAD

**Issue by bronger** [scafroglia93/blocklists#18]
I stumbled upon blocklists-sentinelone.txt because it contains telepolis.de, a renowned German news site. I understand that it was target of some attack but this does not justify a general, long-term blocking. The attack was very limited and has been dealt with.

I see some further respectable German newspapers in the list.

It undermines the usefulness of the whole file for me.

**Comment by scafroglia93** [comment]
https://github.com/scafroglia93/blocklists/commit/53903bcde68f0897d244b2f6888bc6145e67f5f9
