### ISSUE TITLE
A lot (51) invalid domains in your list

### ISSUE THREAD

**Issue by beerisgood** [scafroglia93/blocklists#5]
Same problem like https://github.com/scafroglia93/blocklists/issues/4 but now with 51! invalid domains.
PiHole only list some as example:

[i] Target: https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt
  [✓] Status: Retrieval successful
  [i] Received 33069 domains, 51 domains invalid!
      Sample of invalid domains:
      - abastostelano.comÊ
      - alhumaideist.comÊ
      - amicalifeinsurrance.comÊ
      - askach.infoÊ
      - automotors-france.comÊ

**Comment by scafroglia93** [comment]
many thanks

fixed (was silverterrrier 2019 import error)
