### ISSUE TITLE
The line "aggiornamento. info" break everything with the info TLD due to space character

### ISSUE THREAD

**Issue by crssi** [scafroglia93/blocklists#8]
`aggiornamento. info` <- see the space after the dot `.`.

See more here: https://github.com/ghacksuserjs/ghacks-user.js/issues/975

Cheers

**Comment by scafroglia93** [comment]
> `aggiornamento. info` <- see the space after the dot `.`.
> 
> See more here: https://github.com/ghacksuserjs/ghacks-user.js/issues/975
> 
> Cheers

Can you open an issue please

**Comment by crssi** [comment]
> Can you open an issue please

Don't understand what you mean. Isn't this very issue the real issue?

Cheers and thank you for quick fix
